import { Metadata } from 'next'
import { PageHero } from '@/components/sections/page-hero'
import { MessageCircle, Search, HelpCircle, FileText, Settings, BookOpen } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Help Center | Expert GeM Intelligence Platform',
  description: 'Find answers, guides, and support for your GeM procurement journey.',
}

const faqs = [
  {
    category: 'Getting Started',
    questions: [
      { q: 'How do I register my business on GeM?', a: 'Business registration requires your PAN, Aadhaar, and UDYAM certificate. Our consulting team provides end-to-end assistance to ensure your profile is verified quickly.' },
      { q: 'What is Vendor Assessment?', a: 'Vendor Assessment is a mandatory quality check by QCI for OEMs on GeM. It evaluates your manufacturing capacity, quality control, and financial health.' }
    ]
  },
  {
    category: 'Tenders & Bidding',
    questions: [
      { q: 'How does the AI Tender Analyzer work?', a: 'The AI Analyzer reads 100+ page tender documents in seconds and extracts exact eligibility criteria, identifying if your profile meets the requirements.' },
      { q: 'Can you help us win a specific tender?', a: 'Yes! We offer End-to-End Tender Management where our experts handle the documentation, pricing strategy, and technical bid submission.' }
    ]
  },
  {
    category: 'Compliance & Authorization',
    questions: [
      { q: 'How do I get OEM Authorization?', a: 'You need an authorization code generated by the OEM on their GeM panel. We help resellers coordinate with OEMs to secure these codes.' },
      { q: 'What happens if my certificate expires?', a: 'Your catalog may be deactivated. The Compliance Center tracks all your document expiry dates and sends automated alerts before they lapse.' }
    ]
  }
]

export default function HelpCenterPage() {
  return (
    <>
      <PageHero
        title="Help Center"
        description="Everything you need to know to succeed on the Government e-Marketplace."
      />

      <section className="py-16 sm:py-24 bg-slate-50 relative overflow-hidden">
        {/* Background elements */}
        <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
          <div className="absolute -top-[20%] -right-[10%] w-[50%] h-[50%] rounded-full bg-primary/5 blur-3xl"></div>
          <div className="absolute top-[60%] -left-[10%] w-[40%] h-[40%] rounded-full bg-blue-50 blur-3xl"></div>
        </div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          
          {/* Search Bar Placeholder */}
          <div className="bg-white p-2 rounded-2xl shadow-xl shadow-slate-200/50 flex items-center border border-slate-200 mb-16 ring-1 ring-slate-900/5">
            <div className="pl-4 pr-2 text-slate-600">
              <Search className="w-6 h-6" />
            </div>
            <input 
              type="text" 
              placeholder="Search for articles, guides, or FAQs..." 
              className="w-full bg-transparent border-none outline-none py-4 text-slate-700 placeholder:text-slate-600 text-lg"
            />
            <button className="bg-primary hover:bg-primary/90 text-primary-foreground px-8 py-3.5 rounded-xl font-semibold transition-all">
              Search
            </button>
          </div>

          <div className="grid md:grid-cols-3 gap-6 mb-16">
            <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow cursor-pointer group">
              <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <BookOpen className="w-6 h-6" />
              </div>
              <h3 className="font-bold text-slate-900 text-lg mb-2">Platform Guides</h3>
              <p className="text-slate-500 text-sm">Learn how to use the Intelligence tools.</p>
            </div>
            <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow cursor-pointer group">
              <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <FileText className="w-6 h-6" />
              </div>
              <h3 className="font-bold text-slate-900 text-lg mb-2">Policy Updates</h3>
              <p className="text-slate-500 text-sm">Latest changes to GeM procurement rules.</p>
            </div>
            <div className="bg-white border border-slate-200 p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow cursor-pointer group">
              <div className="w-12 h-12 bg-purple-50 text-purple-600 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <Settings className="w-6 h-6" />
              </div>
              <h3 className="font-bold text-slate-900 text-lg mb-2">Account Setup</h3>
              <p className="text-slate-500 text-sm">Manage your profile and compliance.</p>
            </div>
          </div>

          {/* FAQs */}
          <div className="space-y-12">
            <div className="text-center mb-10">
              <h2 className="text-3xl font-extrabold text-slate-900 mb-4">Frequently Asked Questions</h2>
              <p className="text-slate-600">Quick answers to common questions about GeM and our platform.</p>
            </div>

            {faqs.map((section, idx) => (
              <div key={idx} className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm">
                <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
                  <HelpCircle className="w-5 h-5 text-primary" />
                  {section.category}
                </h3>
                <div className="space-y-6">
                  {section.questions.map((item, i) => (
                    <div key={i} className="pb-6 border-b border-slate-100 last:border-0 last:pb-0">
                      <h4 className="font-semibold text-slate-900 text-lg mb-2">{item.q}</h4>
                      <p className="text-slate-600 leading-relaxed">{item.a}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Chat CTA */}
          <div className="mt-16 bg-primary text-primary-foreground rounded-3xl p-8 sm:p-12 text-center relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
              <div className="absolute top-0 right-0 w-64 h-64 bg-slate-100 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3"></div>
            </div>
            <div className="w-16 h-16 bg-slate-100 rounded-2xl flex items-center justify-center mx-auto mb-6 backdrop-blur-sm">
              <MessageCircle className="w-8 h-8 text-slate-900" />
            </div>
            <h3 className="text-2xl sm:text-3xl font-bold mb-4">Still need help?</h3>
            <p className="text-primary-foreground/80 text-lg mb-8 max-w-xl mx-auto">
              Our Expert AI chatbot is available 24/7. Click the chat icon in the bottom right corner of your screen to get instant answers.
            </p>
          </div>

        </div>
      </section>
    </>
  )
}
